### PR TITLE
Make #[serde(alias)] works in #[serde(flatten)] context

### LINKED ISSUE #1504: Field aliases do not work in combination with `flatten`
Field aliases as introduced in https://github.com/serde-rs/serde/pull/1458 do not work when deserializing "flattened" structures.

### Expected behavior

Field aliases should work when deserializing "flattened" structures.

### Observed behavior

Field aliases do not work when deserializing "flattened" structures.

### How to reproduce

The following code can be used to reproduce the problem, also available as Rust Playground snippet [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2a24a58747f7c27840774e2492fa5d1e).

```
use serde::{Deserialize, Serialize};
use serde_json;

#[derive(Serialize, Deserialize)]
pub struct A {
    #[serde(rename = "y", alias = "z")]
    x: i64,
}

#[derive(Serialize, Deserialize)]
pub struct B {
    #[serde(flatten)]
    a: A,
}

fn main() -> Result<(),Box<std::error::Error>> {
     let i = r#"{ "z": 12 }"#; // using r#"{ "y": 12 }"# will work.
     let b: B = serde_json::from_str(i)?;
     assert_eq!(b.a.x,12);
     Ok(())
}
```

### PR DESCRIPTION
**Pull request by bebecue**
fix #1504

### CODE REVIEW

**Comment by oli-obk** [comment]
Please also add a few tests for a struct like the one from the issue.

File: test_suite/tests/test_annotations.rs [hunk 1]
```diff
@@ -780,7 +780,7 @@ fn test_rename_enum() {
             Token::StructVariant {
                 name: "AliasEnum",
                 variant: "sailor_moon",
-                len: 3,
```
Comment (jonasbb) [inline test_suite/tests/test_annotations.rs:783]: This seems wrong. The struct still only has a length of 3,since three fields are emitted. Not 5 just because there are five field names and aliases.

Comment (dtolnay) [reply test_suite/tests/test_annotations.rs:783]: In the serde data model, the struct definitely has 5 fields (some of which are optional, some subsets of which are mutually exclusive).

The exact number of Rust fields that the deserialized Rust representation ends up storing doesn't seem relevant. If we wrote a Deserialize impl that stored none of them, it doesn't make a difference to the Deserializer. Or compare with how `#[serde(transparent)] struct Struct(i32);` deserializes using deserialize_i32, not deserialize_newtype_struct, even with the deserialized Rust representation `Struct` being a struct not an int -- that isn't relevant.

**Comment by bebecue** [comment]
> Please also add a few tests for a struct like the one from the issue.

Added in https://github.com/serde-rs/serde/pull/2387/commits/01da3f79c9a41220174e8b7e89c3e836325e97ff

**Review by oli-obk — APPROVED** [review]

**Review by dtolnay — COMMENTED** [review]
Thanks!

In https://github.com/serde-rs/serde/pull/2160#pullrequestreview-1143343662 I was hopeful that somebody would look into what possibility of breakage this has for existing formats, but in the absence of anyone having been willing to do that, I think it will be all right to reassess based on any reported consequences.

**Comment by janik-cloudflare** [comment]
Thanks a ton @dtolnay! Just ran into this and it's fantastic to see that a fix is already out. Really appreciate your work on serde :)

**Comment by banool** [comment]
> I was hopeful that somebody would look into what possibility of breakage this has for existing formats, but in the absence of anyone having been willing to do that, I think it will be all right to reassess based on any reported consequences.

I know I'm well and truly late to the party hahah but this change did break some of our code.

At a high level you can see the issue like this:
```
git clone git@github.com:aptos-labs/aptos-core.git
# Change serde version in Cargo.toml to 1.0.153
cd testsuite/generate-format
cargo run -- --corpus aptos
```

With 1.0.152 this code works without error.

I tried the latest version of serde (1.0.188 at the time of writing) and the issue seems to persist.

I'm still trying to figure out how this change actually breaks our code, I just wanted to report in with an instance of a breakage.

**Comment by banool** [comment]
btw I looked into some issues in this repo. I know serde complies with semver but I also know that that only applies to public APIs. I'm not 100% sure if this qualifies as a breaking change. I'll try figure that out and open a new issue if so.

**Comment by banool** [comment]
Moving to this issue now: https://github.com/serde-rs/serde/issues/2627.
