### PR TITLE
Handle various degenerate cases

### LINKED ISSUE #676: Empty braced struct generates dead code
```rust
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
}
```

The generated code (cleaned up) looks like:

```rust
impl Deserialize for Config {
    fn deserialize<D>(deserializer: &mut D) -> Result<Config, D::Error>
        where D: Deserializer
    {
        enum Field {}

        impl Deserialize for Field {
            /* ... */
        }

        struct Visitor<D: Deserializer>(PhantomData<D>);

        impl<D: Deserializer> Visitor for Visitor<D> {
            type Value = Config;
            fn visit_seq<V>(&mut self, mut visitor: V) -> Result<Config, V::Error>
                where V: SeqVisitor
            {
                try!(visitor.end());
                Ok(Config{})
            }
            fn visit_map<V>(&mut self, mut visitor: V) -> Result<Config, V::Error>
                where V: MapVisitor
            {
                // ERROR: irrefutable while-let pattern
                while let Some(key) = try!(visitor.visit_key::<Field>()) {
                    match key {}
                }
                try!(visitor.end());
                Ok(Config{})
            }
        }

        const FIELDS: &'static [&'static str] = &[];
        deserializer.deserialize_struct("Config", FIELDS, Visitor::<D>(PhantomData))
    }
}
```

This is an error on Rust 1.16. We need to omit the Field enum and the while loop in the empty braced struct case.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #676 and adds tests for #677.

### CODE REVIEW

File: serde_codegen/src/de.rs [hunk 1]
```diff
@@ -536,7 +528,20 @@ fn deserialize_item_enum(
         };
         variant_arms.push(arm);
     }
-    variant_arms.extend(ignored_arm.into_iter());
+
+    let match_variant = if variant_arms.is_empty() {
+        // This is an empty enum like `enum Impossible {}` or an enum in which
+        // all variants have `#[serde(skip_deserializing)]`.
+        quote! {
+            visitor.visit_variant::<__Field>().map(|impossible| match impossible {})
```
Comment (oli-obk) [inline serde_codegen/src/de.rs]: also add the `// FIXME: Replace once we drop support for Rust 1.15:` comment

Comment (dtolnay) [inline serde_codegen/src/de.rs]: Added in b01c23b5ee3ba96c286b22fb8f958ea6b2576fde. This case is a little different because `visit_variant` returns `Result<__Field>` rather than `Result<Option<__Field>>`.
