### PR TITLE
Remove "_error" from de::Error methods, add string argument to Error::syntax()

### LINKED ISSUE #125: Extend `de::Error` to signal more cases of errors
Maybe we could strip off the `_error` suffix, it's already clear due to the name of the trait. I usually call these method using `de::Error::syntax_error()`.

I often parse some data coming in via `visit_str` and other visitors into specialized types. There are additional error cases when a constraint is not met, for example parsing a string as UUID. How to handle such errors?

One could argue that these errors are not related to serialization/deserialization, but validation. That means that validation errors should be embedded (like it's done in `io::Error`?).

Otherwise we could add some more methods to `de::Error`. I'd like to change `fn syntax_error() -> Self` to `fn syntax(msg: &str) -> Self` because I (ab)use it to signal validation errors and have no way to transport which constraint was violated. Which error conditions you like to see included?

Current trait definition of `de::Error`:
```rust
pub trait Error {
    fn syntax_error() -> Self;

    fn end_of_stream_error() -> Self;

    fn unknown_field_error(field: &str) -> Self;

    fn missing_field_error(field: &'static str) -> Self;
}
```

### PR DESCRIPTION
**Pull request by erickt**
Closes #125

### CODE REVIEW

File: serde/src/de/impls.rs [hunk 1]
```diff
@@ -200,12 +200,12 @@ impl Visitor for CharVisitor {
         let mut iter = v.chars();
         if let Some(v) = iter.next() {
             if iter.next().is_some() {
-                Err(Error::syntax_error())
+                Err(Error::syntax("sepected a character"))
```
Comment (tomprogrammer) [inline serde/src/de/impls.rs]: typo: expected

Comment (erickt) [inline serde/src/de/impls.rs]: fixed!
